"use strict";
const _1 = require('../plugin-system/');
const one_1 = require("./one");
const two_1 = require("./two");
const three_1 = require("./three");
const four_1 = require("./four");
const five_1 = require("./five");
const six_1 = require("./six");
const seven_1 = require("./seven");
const eight_1 = require("./eight");
const nine_1 = require("./nine");
const ten_1 = require("./ten");
const pm = new _1.PluginManager();
pm.addPlugin('one', new one_1.default());
pm.addPlugin('two', new two_1.default());
pm.addPlugin('three', new three_1.default());
pm.addPlugin('four', new four_1.default());
pm.addPlugin('five', new five_1.default());
pm.addPlugin('six', new six_1.default());
pm.addPlugin('seven', new seven_1.default());
pm.addPlugin('eight', new eight_1.default());
pm.addPlugin('nine', new nine_1.default());
pm.addPlugin('ten', new ten_1.default());
pm.determineOrder();
pm.loadAll();
